### ISSUE TITLE
LICENCSE

### ISSUE THREAD

**Issue by akamaster** [KwangHoonAn/PACT#5]
Dear @KwangHoonAn 
Thank you for your code and efforts in reproducing PACT. Would you please consider adding some open-source license so it would be easier to experiment with your code for people in industry?

Thanks a lot!

**Comment by KwangHoonAn** [comment]
Hi,
Apology for late response, have been busy with my job :)
Will add a license today

**Comment by KwangHoonAn** [comment]
Done !

**Comment by akamaster** [comment]
Thanks a lot!
